function addTwo (int& num) -> None {
    num += 2;
}

function getMax (int a, int b) -> int {
    if (a >= b) {
        return a;
    }
    return b;
}

function conditionalCheck (int a) -> None {
    if (a == 1) {
        print("1");
    }
    else if (a == 2) {
        print("2");
    }
    else {
        print("something");
    }
}

function main () -> None {
    // Variable Declarations
    int a = 1;
    float b = 3.14159;
    char c = 'z';
    string d = "hello world";
    bool e = true; // or false

    int n = 1;
    addTwo(n);
    print(n);
    
    for (i in 0..10) {
        print(i);
    }

    int i = 0;
    while (i < 10) {
        print(i);
        i += 1;
    }
}